### ISSUE TITLE
Zero output

### ISSUE THREAD

**Issue by SatoshiNakamotoBitcoins** [TheRealLordFractal/Bip39Helper#2]
When I apply the command I got zero output; it seems like Brainflayer doesn't accept the input of ./bip39helper, ofcourse the -i flag is not applied. I also copied all the brainflayer files into the Bip39Helper folder...what I'm doing wrong ??

By the way...in the example command you refer to testfile.blm I think you suppose to mean testfile.blf...

![command](https://user-images.githubusercontent.com/45945164/54270785-7e621b80-4580-11e9-8cef-2e7b66df2cbf.PNG)
![output](https://user-images.githubusercontent.com/45945164/54270853-a0f43480-4580-11e9-8a68-5efef44700be.PNG)

**Comment by hamnaz** [comment]
same result here

**Comment by hamnaz** [comment]
even this error too

./bip39helper -n 900000 | ../brainflayer/brainflayer -a -v  -o foundkeys.txt -b 11fulljf.blf
failed to open bloom filter '11fulljf.blf': No such file or directory

**Comment by SatoshiNakamotoBitcoins** [comment]
@hamnaz that error I also recieved after playing around...;-)

**Comment by TheRealLordFractal** [comment]
Fixed, it was using the old version, which would create a 12words.txt  Issue should be fixed with new version

**Comment by TheRealLordFractal** [comment]
now when you type ./bip39helper you will see default 5 line output, that confirms now you can pipe it to brainflayer, 

Edit:  I also checked you can run bip39helper from any directory and point to files in brainflayer, see screenshot

![Screen Shot 2019-03-13 at 5 15 08 PM](https://user-images.githubusercontent.com/40230109/54322935-568cab00-45b4-11e9-8de3-1b755a52a319.png)

Please update to 1.0.1

**Comment by hamnaz** [comment]
what is table file ?
what a use for that here as ?
ecm2table generator binary in brainflayer folder
what is command to generate table ?
can you explain more about table working ?

**Comment by hamnaz** [comment]
also you are useing blm extension
brainflayer uses blf extension

**Comment by SatoshiNakamotoBitcoins** [comment]
@TheRealLordFractal @hamnaz Great Real Lord...now it works like a charm...we can Bip39 away...;-)

Hamnaz...tablefile.tab is to distribute brainflayer over more instances applying flag -n...for example 8 cores... -n 1/8 -n 2/8 -n 3/8 ...etc

**Comment by hamnaz** [comment]
chawla@i3-6100:~/Bip39Helper$ ./bip39helper -n 9000000 | ../brainflayer/brainflayer -v -o foundkeys.txt -b ../brainflayer/11fulljf.blf
 rate:      0.00 p/s found:     0/0          elapsed:   43.396 s

**Comment by hamnaz** [comment]
chawla@i3-6100:~/Bip39Helper$ ./bip39helper -n 900000 | ../brainflayer/brainflayer -a -v -o foundkeys.txt -b ../brainflayer/11fulljf.blf
 rate:      0.00 p/s found:     0/0          elapsed:    3.446 s
chawla@i3-6100:~/Bip39Helper$ ./bip39helper -n 900000 | ../brainflayer/brainflayer -a -v -o foundkeys.txt -b ../brainflayer/11fulljf.blf -n 1/2
 rate:      0.00 p/s found:     0/0          elapsed:    3.484 s
chawla@i3-6100:~/Bip39Helper$ ./bip39helper -n 9000000 | ../brainflayer/brainflayer -a -v -o foundkeys.txt -b ../brainflayer/11fulljf.blf -n 1/2
 rate:      0.00 p/s found:     0/0          elapsed:   40.965 s
chawla@i3-6100:~/Bip39Helper$ ./bip39helper -n 9000000 | ../brainflayer/brainflayer -v -o foundkeys.txt -b ../brainflayer/11fulljf.blf -n 1/2
 rate:      0.00 p/s found:     0/0          elapsed:   40.076 s
chawla@i3-6100:~/Bip39Helper$ ./bip39helper -n 9000000 | ../brainflayer/brainflayer -v -o foundkeys.txt -b ../brainflayer/11fulljf.blf
 rate:      0.00 p/s found:     0/0          elapsed:   43.396 s
chawla@i3-6100:~/Bip39Helper$ ^C
chawla@i3-6100:~/Bip39Helper$ ./bip39helper -n 9000000 | ../brainflayer/brainflayer -v -o foundkeys.txt -b ../brainflayer/13mar19.blf
 rate:      0.00 p/s found:     0/0          elapsed:   34.737 s

**Comment by hamnaz** [comment]
when i run command
no result infront
back ground 12words.txt expanding in size

**Comment by SatoshiNakamotoBitcoins** [comment]
@hamnaz copy alle the "files" including .blf off brainflayer into bip39helper folder and it will work...

According to -b flag in CLI type -b 13mar19.blf (instead of -b ../brainflayer/13mar19.blf)

**Comment by SatoshiNakamotoBitcoins** [comment]
@hamnaz I see you apply ./bip39helper but you need to apply the updated version ./bip39helper-LinuxX64 see releases section...

**Comment by hamnaz** [comment]
it generate 12words random ?

**Comment by SatoshiNakamotoBitcoins** [comment]
@hamnaz yes...random...it enables brainflayer also to act random now...stead only incremental...

**Comment by TheRealLordFractal** [comment]
I named my file .blm for bloom filter, but the file name can be named anything you want after the -b flag in brainflayer @hammaz 

the .tab file allows you to run multiple process's of brainflayer and use the same memory space, its must faster then calling the process seperatly

you can generate that file in the brainflayer directory,  I choose size  575M
./ocmtabgen 575M tabfile.tab
and then you call it from each progress as you can see in the example above.

**Comment by prodnet** [comment]
Hi,

I do not understand how this generator works with Brainflayer?

Source: https://iancoleman.io/bip39/#english

Example :

BIP39 Mnemonic : omit version mad inherit sustain bar isolate onion unusual paper top pigeon
Address : 1M9Seasx4iVTPC5N4YhjhqsN8J3pyUJqRc

Hash160 : dcfb40d493c2396bd4017cdef2d99c60240f9bab
Private Key : L4ARUfFfeFV1HhW52H3F6Hc84vvBGU2CP2HLou9bZHSG81jsrk5A


I added to the bloom file the hash160 "dcfb40d493c2396bd4017cdef2d99c60240f9bab" but Brainflayer does not find anything ... please explain how it works exactly!

Thanks.

**Comment by SatoshiNakamotoBitcoins** [comment]
@prodnet Brainflayer makes a hash of the 12 word phrase and compares it with the bloomfilter...

Cheers

**Comment by prodnet** [comment]
Yes but the hash  that the Brainflayer produce is not the same with that in my example"dcfb40d493c2396bd4017cdef2d99c60240f9bab"... where is the problem?

**Comment by SatoshiNakamotoBitcoins** [comment]
@prodnet your example 12 words phrase must give the following address according to sha256

![hash](https://user-images.githubusercontent.com/45945164/54450394-94263b00-4750-11e9-97b6-0ce2dbdd8f85.PNG)

**Comment by SatoshiNakamotoBitcoins** [comment]
@prodnet in your example the WIF private key starts with a "L" that means a compressed address...with your example 12 words phrase that would be...

![hashcompressed](https://user-images.githubusercontent.com/45945164/54450666-452cd580-4751-11e9-8ead-d31200c05ca0.PNG)

**Comment by TheRealLordFractal** [comment]
I checked bip39helper against ian coleman and see attached screen shot, I find hash and it works.  Now everyline going to be valid, no, as the words go into a checksum for the last remaining word. I generated 5 lines out of the 5 lines 2 were valid nmenonic address's.  
![Screen Shot 2019-03-15 at 10 58 08 AM](https://user-images.githubusercontent.com/40230109/54452214-cebcb300-4711-11e9-95b0-1750dc9a604e.png)

**Comment by prodnet** [comment]
Please check with the source below and you will understand that it is not similar

https://iancoleman.io/bip39/#english
BIP39 Mnemonic : omit version mad inherit sustain bar isolate onion unusual paper top pigeon

**Comment by prodnet** [comment]
It does not work, we tested it with an entire list of addresses generated with
"iancoleman.io/bip39"
Seed recovery is just a simple hash256 of the seed?
I assure you that something is not working well ...

**Comment by TheRealLordFractal** [comment]
As you can see from above post, I updated it, not all words will pass the checksum, however I verified the output from bip39helper to ian colemans and you can see its valid.

**Comment by SatoshiNakamotoBitcoins** [comment]
@prodnet I did...see attachment below here the bip39 generates bip39 seed...that's not the same as Real Lord BIP39helper does work; it generates a single address...

It's just fine...

![bip39](https://user-images.githubusercontent.com/45945164/54452314-2e887d80-4755-11e9-9893-6a60b7f4a06f.PNG)

**Comment by prodnet** [comment]
If everything works correctly, why does the address and hash160 are not similar to those generated by "iancoleman.io"?
![1](https://user-images.githubusercontent.com/43401428/54453338-65f82980-4757-11e9-88b7-90cfb9cceaed.PNG)
![2](https://user-images.githubusercontent.com/43401428/54453339-65f82980-4757-11e9-82ce-33edd57324b4.PNG)
![3](https://user-images.githubusercontent.com/43401428/54453340-6690c000-4757-11e9-9838-51c0fbce224a.PNG)

**Comment by prodnet** [comment]
As you can see, the addresses and hash160 are differents :)

**Comment by TheRealLordFractal** [comment]
The other thing are you using bip39 or bip44, I can generate an address almost every time, the checks against brainflayer.. I am not following what the problem is
also uploading the old 1628 mnemonic phrase list for wallets before july 2014
check files in branch

**Comment by SatoshiNakamotoBitcoins** [comment]
@prodnet Check link below...when a single 12 word phrase is applied with this generator the output of the Real Lord is correct...

https://brainwalletx.github.io/#generator

The same 12 word phrase in according to a bip39 seed gives another outcome (applied to hunderd of addresses)

Get the picture...;-)

**Comment by TheRealLordFractal** [comment]
I also imported word phrase to electrum wallet to verify address, worked every time, imported 3 address's that were randomly generated.

Also @SatoshiNakamotoBitcoins the old list I just uploaded from 2014 found 2 address's within 15 minutes that had scraps .0000000546 BTC lol, so the old list works too.

**Comment by prodnet** [comment]
If we do a simple hash256 of BIP39 recovery phrase, the generated address is correct.
But the most softwares and hardware wallets (trezor, ledger, ..etc)  uses a Derivation Path :
BIP44 Multi-Account Hierarchy for Deterministic Wallets
BIP32 Hierarchical Deterministic Wallets

In conlusion, Brainfalyer do not support the Derivation Path,  
which greatly limits the use of this generator.

Are I wrong somewhere?

**Comment by TheRealLordFractal** [comment]
@prodnet I uploaded the old electrum phrase list as well all electrum wallets before 2014 July, use the old 1628 Phrase list which applicable and works with brainflayer

**Comment by prodnet** [comment]
Thanks but you did not reply to my last post ..:)

**Comment by SatoshiNakamotoBitcoins** [comment]
@prodnet You're correct Brainflayer...doesn't support derivation path...

**Comment by prodnet** [comment]
Maybe someone could adapt Brainflayer, to support derivative path ...
It would be great for all of us ... :)

**Comment by SatoshiNakamotoBitcoins** [comment]
@prodnet This person did a try...

https://github.com/ipsBruno/brute-force-seed-bitcoin

**Comment by stuballs-pixel** [comment]
hello please help i get this
./biphelper -l 6 | ../brainflayer/brainflayer -v -m tabfile.tab -o foundkeys.txt -b btc.blf
failed to open ecmult table 'tabfile.tab': Incorrect file size
Traceback (most recent call last):
  File "biphelper.py", line 109, in init biphelper
  File "biphelper.py", line 100, in biphelper.main
  File "biphelper.py", line 48, in biphelper.generate
IOError: [Errno 32] Broken pipe

I have created a 600M tabfile with ecmtabgen when i try a 575M it says cannot allocate memory. I am really stuck.

**Comment by stereonov** [comment]
@SatoshiNakamotoBitcoins 

Hello, great project 2 days and still can't make it work with brainflayer...
Same issue with hamnaz, zero output.
I saw your comments, so I download latest version, compile as 'Read me" file providing:
`gcc -v -Os -I /usr/include/python2.7/ -L /usr/local/lib/python2.7/  -o bip39helper bip39helper.c  -lpython2.7  -lpthread -lm -lutil 
-ldl`

and copy all files from brainflayer to 'Bip39Helper-1.02' folder.

`./bip39helper -n 50000 | ./brainflayer -v -b btcaddress.blf -o FOUND.txt`

output:
` rate:      0.00 p/s found:     0/0          elapsed:    0.018 s`

P.s. If use './bip39helper-LinuxX64' instead './bip39helper' as you mention, it didn't work at all.

I'm using ubuntu, can you tell me why isn't working?
Thanks in advance!

**Comment by SatoshiNakamotoBitcoins** [comment]
Hi @stereonov 

Maybe you have to try something like this:

./bip39helper -l 12 | ../brainflayer/brainflayer -v -m tablefile.tab -o foundkeys.txt -b testfile.blf

** Note in Version 1.02 I added the -l for words per line tag, and removed having to specify the number of lines you want to create since this is designed to be piped write to brainflayer per example

So drop the -n flag and add the -l flag (in this example 12 words; which is common) don't forget to add the two dots for the execute command of /brainflayer so | ../brainflayer (yes also a SPACE between | and the two dots)

Does function brainflayer properly in the authentic mode??

Yes great...No...maybe you can try this makefile...

https://anonfile.com/V5SbPdubo5/Makefile

Cheers Satoshi

**Comment by SatoshiNakamotoBitcoins** [comment]
@stereonov 

Also I would advise you to apply the latest version biphelper-102a-LinuxX64

https://github.com/TheRealLordFractal/Bip39Helper/releases/tag/1.02a

Make sure that the file and the execute command are named the same in this case ./biphelper-102a-LinuxX64

What also could help is to COPY the .blf file ALSO in the biphelper folder...(so a copy with brainflayer and biphelper folder)

**Comment by stereo4** [comment]
Hi, I am using the latest version 1.02 (1.02 version is newest from 1.02a right?), also I have brainflayer and biphelper on the same folder.
Also renamed compile like this:
`gcc -v -Os -I /usr/include/python2.7/ -L /usr/local/lib/python2.7/ -o biphelper-102-LinuxX64 biphelper-102-LinuxX64.c -lpython2.7 -lpthread -lm -lutil -ldl`

Then execute:
`./biphelper-102-LinuxX64 -l 12 | ../brainflayer/brainflayer -v -o FOUND.txt -b btcaddress.blf`

results:
`biphelper-102-LinuxX64: option -l not recognized
	 for help use --help
 rate:      0.00 p/s found:     0/0          elapsed:    0.019 s`

Again, no idea why I can't make this work...

Did this keep some kind of cache, why still not recognize -l flag? If I use -n flag instead without brainflayer, it will create a '12words.txt' file which is from the old version and supposed to be removed at the new version. Are you sure the files are updated?

Brainflayer works great in general without bip39helper...

**Comment by stereo4** [comment]
Okay figure it out.
After extract files need to rename file 'biphelper.c' to 'biphelper-102a-LinuxX64' and compile:
`gcc -v -Os -I /usr/include/python2.7/ -L /usr/local/lib/python2.7/ -o biphelper-102a-LinuxX64 biphelper-102a-LinuxX64.c -lpython2.7 -lpthread -lm -lutil -ldl`

Then works like a charm.
Thanks!!

Still not get it how to make tab file work.
I have generate the tab file but no idea how to add  '-n 1/4 -n 2/4 -n 3/4 -n 4/4' into tab file.
Can you help please?

Thank you so much, appreciate it!

**Comment by SatoshiNakamotoBitcoins** [comment]
@stereo4 Great to hear you figured it out...it was also possible to download only the compiled file (this was already correct named) and than you were ready to go...;-)

Regarding flag -m (generated with ecmtabgen) look at the repo... https://github.com/ryancdotorg/brainflayer

![1](https://user-images.githubusercontent.com/45945164/80858857-89807b00-8c5c-11ea-9c01-65a08e58ea36.PNG)
There is a "executable" within the brainflayer folder you only have to run it to create this file...after that you have only to apply the flag -m ecmtabgen.tab (for example this file name) than you can apply the -n flag...to divide your workload...

Cheers Satoshi

**Comment by stereo4** [comment]
@SatoshiNakamotoBitcoins

Feeling bad to not get it... I truly thank you for your time...

Tried like this but still in 1 terminal doesn't get me the results of 4 terminals, it's still using only 1 core:
`./biphelper-102a-LinuxX64 -l 12 | ../brainflayer/brainflayer -v -m tabfile.tab -f btcaddress.bin -o FOUND.txt -b btcaddress.blf -n 1/4 -n 2/4 -n 3/4 -n 4/4`

How to apply it? Can you please provide an example?
Thanks again!

**Comment by SatoshiNakamotoBitcoins** [comment]
Not feeling bad...and no probs at all...we nearly there...

You have to open 4 "windows" in the CLI so 4 instances...so your command here above is OK...only at the end for "window 1" -n 1/4 ...than "window 2" -n 2/4 at the end and so on for "window 3" and "window 4" (natively brainflayer is not multithreaded...to divide the workload with flag -n it will act like...)

**Comment by SatoshiNakamotoBitcoins** [comment]
@stereo4 have a look here above mate...

Cheers Satoshi

**Comment by stereo4** [comment]
@SatoshiNakamotoBitcoins

Oh, I was working brainflayer like this for a long time (one flag at each terminal) but I thought that with tab file the command should be all flags in one terminal, my bad.

Thank you so much for your time, highly appreciate it!

**Comment by stereo4** [comment]
@SatoshiNakamotoBitcoins 

Actually I do have one more question, I run `./biphelper-102a-LinuxX64 -l 12` as a test to check the result and I have noticed that the 12 words passphrase has a space before the first word. I wonder if brainflayer did not found anything because of that 'space' character or if it skip it and read passphrase normally.

Thanks again!

**Comment by SatoshiNakamotoBitcoins** [comment]
@stereo4 

The 1.02 a version tackled this issue...

![1](https://user-images.githubusercontent.com/45945164/80945845-12c6b780-8ded-11ea-93a9-b3d749a72afe.PNG)

Cheers Satoshi

**Comment by stereo4** [comment]
@SatoshiNakamotoBitcoins
@TheRealLordFractal 

I know, I have been noticed that. At old version there was one space before the first word and one space after the last word, but now at latest version the space after the last word has been fixed but the space before the first word is exist.

Take a look this example:
`./biphelper-102a-LinuxX64 -l 12`
Output:
![bip39helper](https://user-images.githubusercontent.com/47362249/80954112-68a75980-8e05-11ea-82fe-30f96022ebd1.png)


As you can see the leading space is exist!

But here is if I use SED to remove the first space:
`./biphelper-102a-LinuxX64 -l 12 | sed 's/^ *//g'`
Output with SED:
![bip39helper-with-sed](https://user-images.githubusercontent.com/47362249/80954134-752bb200-8e05-11ea-814b-5f274773d34f.png)


With SED the leading space has been removed!

The crazy thing is that when I use 'biphelper with brainflayer without SED' I get about 76.000 p/s but when I use 'biphelper with brainflayer with SED' I get 84.000 p/s. So if you guys remove the leading space maybe brainflayer be faster than now.

P.s. I'm a big fun of brainflayer and your project as well. I love the technology all around this, congrats!

**Comment by SatoshiNakamotoBitcoins** [comment]
@stereo4 Ok great observation of you!! At the moment SED will be a work around for you (you even got a higher throughput) maybe the dev of biphelfper our great friend @TheRealLordFractal will be so kind to adjust the source code...

Cheers Satoshi

**Comment by stereo4** [comment]
@SatoshiNakamotoBitcoins 
Yeap, wish he will do that for us.

Thanks once again dear friend,
Wishing all the best!

**Comment by SatoshiNakamotoBitcoins** [comment]
@stereo4 You are welcome mate...also the best wishes for you and your family!!

**Comment by stereo4** [comment]
Hey @SatoshiNakamotoBitcoins I have a question about brainflayer, it's out of topic, Ryan seems to bee busy to answer but really need to know about this...

I have build brainflayer at Ubuntu 14.04 once is not possible at newest versions, if I upgrade now at the latest Ubuntu version, brainflayer will still working?

Normally it should work once is already build, have you tried it or anyone else?

Thanks again!

**Comment by SatoshiNakamotoBitcoins** [comment]
@stereo4 Hello...yes it should also work with Ubuntu 18.04 for example...

Cheers Satoshi

**Comment by stereo4** [comment]
@SatoshiNakamotoBitcoins Great, I will give it a try, thanks a lot mate!

**Comment by B1012** [comment]
@SatoshiNakamotoBitcoins @TheRealLordFractal  , 
First of all this tool is great , LordFractal 
but do you actually think addresses are being generated from 12 words , i think the 12 words just contains whole wallet info like addresses and privatekeys like you see on electurm or blockchain wallet 
or maybe am wrong , would love to hear your thoughts

**Comment by SatoshiNakamotoBitcoins** [comment]
@B1012 Yes you are correct many wallets are build with those 12 word phrases like electrum...but also nowadays with 24 words with some apps...those words are composed with the BIP39 wordlists https://iancoleman.io/bip39/....regarding the english word list which contains 2048 words so this gives 2048^12 possibilities = 5444517870735015415413993718908291383296...regarding the birthday paradox you only need to brute force 50% of it to find a collision ... happy hunting...

**Comment by B1012** [comment]
@SatoshiNakamotoBitcoins 
i have a question if you or @TheRealLordFractal can answer 
Imagine if i have a privatekey of a address,  is there any way i can find out the string that address is generated from ?

**Comment by stereo4** [comment]
> @SatoshiNakamotoBitcoins
> i have a question if you or @TheRealLordFractal can answer
> Imagine if i have a privatekey of a address, is there any way i can find out the string that address is generated from ?

Not sure about that, if you mean to get public address from a private key, you can use bitaddress.org.

@SatoshiNakamotoBitcoins I just have also a question, is there anyway to make this git to generate more than 12 words? Noticed that if I change the command to `-l 13` or more it doesn't generate words.

Thanks

**Comment by SatoshiNakamotoBitcoins** [comment]
@stereo4 BIP39 works with a seed and root key as you can see with this link ... https://iancoleman.io/bip39/...but but ...there is a way to crack such called deterministic wallets...our friend Vitalik wrote a nice article about this...maybe you want to read... https://bitcoinmagazine.com/articles/deterministic-wallets-advantages-flaw-1385450276... those cracking scripts you can find here... https://github.com/primal100/pybitcointools...

Regarding the length of the words our friend @TheRealLordFractal is the dev of this app...so he can answer you on this...

Be the force with you!

Greetings

S

**Comment by stereo4** [comment]
> 

I really don't understand how to go on this forward. I'm not enough expert to use these cracking scripts.

Hope the dev @TheRealLordFractal could make this great tool to work with 24 words.

**Comment by stereo4** [comment]
> @stereo4 BIP39 works with a seed and root key as you can see with this link ... https://iancoleman.io/bip39/...but but ...there is a way to crack such called deterministic wallets...our friend Vitalik wrote a nice article about this...maybe you want to read... https://bitcoinmagazine.com/articles/deterministic-wallets-advantages-flaw-1385450276... those cracking scripts you can find here... https://github.com/primal100/pybitcointools...
> 
> Regarding the length of the words our friend @TheRealLordFractal is the dev of this app...so he can answer you on this...
> 
> Be the force with you!
> 
> Greetings
> 
> S

I really don't understand how to go on this forward. I'm not enough expert to use these cracking scripts.

Hope the dev @TheRealLordFractal could make this great tool to work with 24 words.
